-- Autor: GitHub Copilot
-- Zusätzliche Wörter für Stadt-Land-Fluss Spiel
-- 1000 neue Wörter, keine Duplikate zu data.sql

-- === ZUSÄTZLICHE STÄDTE (Kategorie 1) ===
INSERT INTO valid_words (category_id, word) VALUES
-- Deutsche Städte
(1, 'Salzgitter'), (1, 'Cottbus'), (1, 'Gera'), (1, 'Zwickau'), (1, 'Iserlohn'),
(1, 'Gütersloh'), (1, 'Schwerin'), (1, 'Düren'), (1, 'Ratingen'), (1, 'Lünen'),
(1, 'Villingen'), (1, 'Marl'), (1, 'Velbert'), (1, 'Minden'), (1, 'Norderstedt'),
(1, 'Rheine'), (1, 'Gladbeck'), (1, 'Viersen'), (1, 'Delmenhorst'), (1, 'Bamberg'),
(1, 'Lüdenscheid'), (1, 'Castrop'), (1, 'Landshut'), (1, 'Aschaffenburg'), (1, 'Bayreuth'),
(1, 'Lüneburg'), (1, 'Celle'), (1, 'Plauen'), (1, 'Neubrandenburg'), (1, 'Dorsten'),
(1, 'Herford'), (1, 'Grevenbroich'), (1, 'Weimar'), (1, 'Fulda'), (1, 'Kerpen'),
(1, 'Rüsselsheim'), (1, 'Gießen'), (1, 'Schwäbisch'), (1, 'Sindelfingen'), (1, 'Rosenheim'),
(1, 'Konstanz'), (1, 'Worms'), (1, 'Stralsund'), (1, 'Marburg'), (1, 'Passau'),
(1, 'Suhl'), (1, 'Lörrach'), (1, 'Greifswald'), (1, 'Eschweiler'), (1, 'Hürth'),
-- Internationale Städte
(1, 'Paris'), (1, 'London'), (1, 'Madrid'), (1, 'Rom'), (1, 'Mailand'),
(1, 'Barcelona'), (1, 'Amsterdam'), (1, 'Brüssel'), (1, 'Wien'), (1, 'Zürich'),
(1, 'Kopenhagen'), (1, 'Stockholm'), (1, 'Oslo'), (1, 'Helsinki'), (1, 'Warschau'),
(1, 'Prag'), (1, 'Budapest'), (1, 'Bratislava'), (1, 'Ljubljana'), (1, 'Zagreb'),
(1, 'Belgrad'), (1, 'Sofia'), (1, 'Bukarest'), (1, 'Riga'), (1, 'Vilnius'),
(1, 'Tallinn'), (1, 'Dublin'), (1, 'Edinburgh'), (1, 'Cardiff'), (1, 'Belfast'),
(1, 'Lissabon'), (1, 'Porto'), (1, 'Valencia'), (1, 'Sevilla'), (1, 'Bilbao'),
(1, 'Neapel'), (1, 'Turin'), (1, 'Bologna'), (1, 'Florenz'), (1, 'Venedig'),
(1, 'Genua'), (1, 'Palermo'), (1, 'Catania'), (1, 'Bari'), (1, 'Verona'),
(1, 'Athen'), (1, 'Thessaloniki'), (1, 'Istanbul'), (1, 'Ankara'), (1, 'Izmir'),
(1, 'Moskau'), (1, 'Petersburg'), (1, 'Kiew'), (1, 'Minsk'), (1, 'Chisinau'),
(1, 'Tiflis'), (1, 'Eriwan'), (1, 'Baku'), (1, 'Almaty'), (1, 'Taschkent'),
(1, 'Peking'), (1, 'Shanghai'), (1, 'Tokio'), (1, 'Osaka'), (1, 'Kyoto'),
(1, 'Bangkok'), (1, 'Manila'), (1, 'Jakarta'), (1, 'Singapur'), (1, 'Kuala'),
(1, 'Hanoi'), (1, 'Seoul'), (1, 'Pyongyang'), (1, 'Rangun'), (1, 'Phnom'),
(1, 'Neu'), (1, 'Los'), (1, 'Chicago'), (1, 'Houston'), (1, 'Phoenix'),
(1, 'Philadelphia'), (1, 'San'), (1, 'Dallas'), (1, 'San'), (1, 'Detroit'),
(1, 'Boston'), (1, 'Washington'), (1, 'Miami'), (1, 'Atlanta'), (1, 'Denver'),
(1, 'Toronto'), (1, 'Montreal'), (1, 'Vancouver'), (1, 'Ottawa'), (1, 'Calgary'),
(1, 'Sydney'), (1, 'Melbourne'), (1, 'Brisbane'), (1, 'Perth'), (1, 'Adelaide'),
(1, 'Kairo'), (1, 'Casablanca'), (1, 'Tunis'), (1, 'Algier'), (1, 'Tripolis'),
(1, 'Lagos'), (1, 'Nairobi'), (1, 'Kapstadt'), (1, 'Johannesburg'), (1, 'Durban'),
(1, 'Rio'), (1, 'São'), (1, 'Buenos'), (1, 'Santiago'), (1, 'Lima'),
(1, 'Bogota'), (1, 'Caracas'), (1, 'Montevideo'), (1, 'Quito'), (1, 'La'),

-- === ZUSÄTZLICHE LÄNDER (Kategorie 2) ===
-- Afrikanische Länder
(2, 'Angola'), (2, 'Botswana'), (2, 'Burkina'), (2, 'Burundi'), (2, 'Benin'),
(2, 'Tschad'), (2, 'Dschibuti'), (2, 'Eritrea'), (2, 'Gabun'), (2, 'Gambia'),
(2, 'Guinea'), (2, 'Elfenbeinküste'), (2, 'Lesotho'), (2, 'Liberia'), (2, 'Madagaskar'),
(2, 'Malawi'), (2, 'Mali'), (2, 'Mauretanien'), (2, 'Mauritius'), (2, 'Mosambik'),
(2, 'Namibia'), (2, 'Niger'), (2, 'Ruanda'), (2, 'Senegal'), (2, 'Sierra'),
(2, 'Somalia'), (2, 'Swasiland'), (2, 'Togo'), (2, 'Sambia'), (2, 'Simbabwe'),
-- Amerikanische Länder
(2, 'Argentinien'), (2, 'Bolivien'), (2, 'Brasilien'), (2, 'Chile'), (2, 'Ecuador'),
(2, 'Guyana'), (2, 'Kolumbien'), (2, 'Paraguay'), (2, 'Peru'), (2, 'Suriname'),
(2, 'Uruguay'), (2, 'Venezuela'), (2, 'Kanada'), (2, 'Mexiko'), (2, 'Guatemala'),
(2, 'Belize'), (2, 'Honduras'), (2, 'Salvador'), (2, 'Nicaragua'), (2, 'Costa'),
(2, 'Panama'), (2, 'Kuba'), (2, 'Haiti'), (2, 'Dominikanische'), (2, 'Jamaika'),
(2, 'Trinidad'), (2, 'Barbados'), (2, 'Bahamas'), (2, 'Antigua'), (2, 'Dominica'),
-- Asiatische Länder
(2, 'Sri'), (2, 'Bhutan'), (2, 'Malediven'), (2, 'Mongolei'), (2, 'Tadschikistan'),
(2, 'Kirgisistan'), (2, 'Turkmenistan'), (2, 'Brunei'), (2, 'Osttimor'), (2, 'Papua'),
(2, 'Fidschi'), (2, 'Salomonen'), (2, 'Vanuatu'), (2, 'Samoa'), (2, 'Tonga'),
(2, 'Kiribati'), (2, 'Tuvalu'), (2, 'Nauru'), (2, 'Palau'), (2, 'Marshallinseln'),
-- Ozeanische Länder
(2, 'Australien'), (2, 'Neuseeland'), (2, 'Mikronesien'),
-- Weitere europäische Länder
(2, 'San'), (2, 'Vatikanstadt'), (2, 'Nordmazedonien'), (2, 'Kosovo'),

-- === ZUSÄTZLICHE FLÜSSE (Kategorie 3) ===
-- Deutsche Flüsse
(3, 'Kinzig'), (3, 'Regnitz'), (3, 'Naab'), (3, 'Regen'), (3, 'Ilz'),
(3, 'Salzach'), (3, 'Enns'), (3, 'Traun'), (3, 'Iller'), (3, 'Günz'),
(3, 'Mindel'), (3, 'Zusam'), (3, 'Schmutter'), (3, 'Paar'), (3, 'Abens'),
(3, 'Große'), (3, 'Kleine'), (3, 'Vils'), (3, 'Naarn'), (3, 'Erlauf'),
(3, 'Ybbs'), (3, 'Melk'), (3, 'Pielach'), (3, 'Traisen'), (3, 'Schwechat'),
(3, 'Fischa'), (3, 'Leitha'), (3, 'March'), (3, 'Thaya'), (3, 'Kamp'),
(3, 'Krems'), (3, 'Perschling'), (3, 'Tulln'), (3, 'Wienfluss'), (3, 'Schwarz'),
(3, 'Enns'), (3, 'Steyr'), (3, 'Krems'), (3, 'Alm'), (3, 'Traun'),
(3, 'Ager'), (3, 'Vöckla'), (3, 'Ach'), (3, 'Mattig'), (3, 'Antiesen'),
(3, 'Salzach'), (3, 'Saalach'), (3, 'Sur'), (3, 'Mur'), (3, 'Mürz'),
-- Internationale Flüsse
(3, 'Moldau'), (3, 'Elbe'), (3, 'Moldava'), (3, 'Morava'), (3, 'Dyje'),
(3, 'Svitava'), (3, 'Svratka'), (3, 'Jihlava'), (3, 'Sazava'), (3, 'Berounka'),
(3, 'Eger'), (3, 'Ohre'), (3, 'Teplá'), (3, 'Radbusa'), (3, 'Mže'),
(3, 'Úhlava'), (3, 'Radbuza'), (3, 'Úslava'), (3, 'Lomnice'), (3, 'Cidlina'),
(3, 'Jizera'), (3, 'Ploučnice'), (3, 'Kamenice'), (3, 'Lužická'), (3, 'Mandava'),
(3, 'Weichsel'), (3, 'Oder'), (3, 'Neiße'), (3, 'Bober'), (3, 'Queis'),
(3, 'Katzbach'), (3, 'Deichsel'), (3, 'Bartsch'), (3, 'Obra'), (3, 'Netze'),
(3, 'Loire'), (3, 'Rhone'), (3, 'Garonne'), (3, 'Dordogne'), (3, 'Charente'),
(3, 'Vienne'), (3, 'Creuse'), (3, 'Indre'), (3, 'Cher'), (3, 'Allier'),
(3, 'Saône'), (3, 'Doubs'), (3, 'Ain'), (3, 'Ardèche'), (3, 'Gard'),
(3, 'Hérault'), (3, 'Aude'), (3, 'Têt'), (3, 'Tech'), (3, 'Agly'),
(3, 'Tarn'), (3, 'Aveyron'), (3, 'Lot'), (3, 'Truyère'), (3, 'Célé'),
(3, 'Durance'), (3, 'Verdon'), (3, 'Var'), (3, 'Argens'), (3, 'Gapeau'),
(3, 'Arve'), (3, 'Isère'), (3, 'Drôme'), (3, 'Ouvèze'), (3, 'Lez'),
(3, 'Vidourle'), (3, 'Vistrenque'), (3, 'Cèze'), (3, 'Ardèche'), (3, 'Chassezac'),
(3, 'Beaume'), (3, 'Eyrieux'), (3, 'Drôme'), (3, 'Roubion'), (3, 'Jabron'),
-- Afrikanische Flüsse
(3, 'Senegal'), (3, 'Volta'), (3, 'Benue'), (3, 'Ubangi'), (3, 'Kasai'),
(3, 'Lualaba'), (3, 'Lomami'), (3, 'Aruwimi'), (3, 'Ituri'), (3, 'Uele'),
(3, 'Sangha'), (3, 'Logone'), (3, 'Chari'), (3, 'Bahr'), (3, 'Sobat'),
(3, 'Atbara'), (3, 'Tekeze'), (3, 'Awash'), (3, 'Omo'), (3, 'Turkana'),
(3, 'Tana'), (3, 'Galana'), (3, 'Pangani'), (3, 'Rufiji'), (3, 'Ruvuma'),
-- Asiatische Flüsse
(3, 'Irrawaddy'), (3, 'Salween'), (3, 'Chao'), (3, 'Ping'), (3, 'Nan'),
(3, 'Yom'), (3, 'Chi'), (3, 'Mun'), (3, 'Songkhram'), (3, 'Ing'),
(3, 'Loei'), (3, 'Huai'), (3, 'Mae'), (3, 'Kok'), (3, 'Fang'),
(3, 'Tarim'), (3, 'Ili'), (3, 'Irtysch'), (3, 'Ob'), (3, 'Jenissei'),
(3, 'Lena'), (3, 'Amur'), (3, 'Ussuri'), (3, 'Sungari'), (3, 'Nonni'),
-- Amerikanische Flüsse
(3, 'Yukon'), (3, 'Mackenzie'), (3, 'Saskatchewan'), (3, 'Nelson'), (3, 'Churchill'),
(3, 'Albany'), (3, 'Moose'), (3, 'Severn'), (3, 'Winisk'), (3, 'Attawapiskat'),
(3, 'Río'), (3, 'Colorado'), (3, 'Gila'), (3, 'Salt'), (3, 'Verde'),
(3, 'Little'), (3, 'Canadian'), (3, 'Cimarron'), (3, 'Washita'), (3, 'Red'),

-- === ZUSÄTZLICHE TIERE (Kategorie 4) ===
-- Meerestiere
(4, 'Wal'), (4, 'Delfin'), (4, 'Hai'), (4, 'Rochen'), (4, 'Thunfisch'),
(4, 'Lachs'), (4, 'Forelle'), (4, 'Karpfen'), (4, 'Hecht'), (4, 'Barsch'),
(4, 'Aal'), (4, 'Sardine'), (4, 'Hering'), (4, 'Makrele'), (4, 'Kabeljau'),
(4, 'Scholle'), (4, 'Seezunge'), (4, 'Heilbutt'), (4, 'Steinbutt'), (4, 'Flunder'),
(4, 'Seehecht'), (4, 'Seelachs'), (4, 'Pollack'), (4, 'Wittling'), (4, 'Schellfisch'),
(4, 'Rotbarsch'), (4, 'Knurrhahn'), (4, 'Leng'), (4, 'Lumb'), (4, 'Dorsch'),
(4, 'Seebär'), (4, 'Seehund'), (4, 'Kegelrobbe'), (4, 'Walross'), (4, 'Seekuh'),
(4, 'Tintenfisch'), (4, 'Krake'), (4, 'Kalmar'), (4, 'Sepia'), (4, 'Nautilus'),
(4, 'Hummer'), (4, 'Krebs'), (4, 'Garnele'), (4, 'Languste'), (4, 'Krill'),
(4, 'Seestern'), (4, 'Seeigel'), (4, 'Seegurke'), (4, 'Qualle'), (4, 'Koralle'),
-- Insekten
(4, 'Käfer'), (4, 'Schmetterling'), (4, 'Libelle'), (4, 'Biene'), (4, 'Wespe'),
(4, 'Hummel'), (4, 'Hornisse'), (4, 'Ameise'), (4, 'Termite'), (4, 'Grille'),
(4, 'Heuschrecke'), (4, 'Gottesanbeterin'), (4, 'Wanze'), (4, 'Zikade'), (4, 'Blattlaus'),
(4, 'Marienkäfer'), (4, 'Maikäfer'), (4, 'Hirschkäfer'), (4, 'Nashornkäfer'), (4, 'Rosenkäfer'),
(4, 'Laufkäfer'), (4, 'Rüsselkäfer'), (4, 'Borkenkäfer'), (4, 'Prachtkäfer'), (4, 'Bockkäfer'),
(4, 'Motte'), (4, 'Spinner'), (4, 'Spanner'), (4, 'Eule'), (4, 'Weißling'),
(4, 'Admiral'), (4, 'Pfauenauge'), (4, 'Bläuling'), (4, 'Falter'), (4, 'Schwärmer'),
(4, 'Fliege'), (4, 'Mücke'), (4, 'Schnake'), (4, 'Bremse'), (4, 'Schwebfliege'),
(4, 'Tanzfliege'), (4, 'Raubfliege'), (4, 'Dickkopffliege'), (4, 'Fleischfliege'), (4, 'Schmeißfliege'),
(4, 'Floh'), (4, 'Laus'), (4, 'Silberfischchen'), (4, 'Kellerassel'), (4, 'Springschwanz'),
-- Reptilien und Amphibien
(4, 'Schlange'), (4, 'Eidechse'), (4, 'Gecko'), (4, 'Leguan'), (4, 'Chamäleon'),
(4, 'Echse'), (4, 'Skink'), (4, 'Waran'), (4, 'Krokodil'), (4, 'Alligator'),
(4, 'Kaiman'), (4, 'Gavial'), (4, 'Schildkröte'), (4, 'Wasserschildkröte'), (4, 'Landschildkröte'),
(4, 'Meeresschildkröte'), (4, 'Sumpfschildkröte'), (4, 'Dosenschildkröte'), (4, 'Schmuckschildkröte'), (4, 'Gelbwangenschildkröte'),
(4, 'Python'), (4, 'Boa'), (4, 'Kobra'), (4, 'Mamba'), (4, 'Viper'),
(4, 'Klapperschlange'), (4, 'Korallenschlange'), (4, 'Natter'), (4, 'Ringelnatter'), (4, 'Schlingnatter'),
(4, 'Frosch'), (4, 'Kröte'), (4, 'Laubfrosch'), (4, 'Wasserfrosch'), (4, 'Grasfrosch'),
(4, 'Springfrosch'), (4, 'Moorfrosch'), (4, 'Teichfrosch'), (4, 'Seefrosch'), (4, 'Kleiner'),
(4, 'Erdkröte'), (4, 'Wechselkröte'), (4, 'Kreuzkröte'), (4, 'Knoblauchkröte'), (4, 'Geburtshelferkröte'),
(4, 'Unke'), (4, 'Molch'), (4, 'Salamander'), (4, 'Axolotl'), (4, 'Olm'),
-- Weitere Säugetiere
(4, 'Waschbär'), (4, 'Stinktier'), (4, 'Nasenbär'), (4, 'Mungo'), (4, 'Erdmännchen'),
(4, 'Surikat'), (4, 'Fossa'), (4, 'Ginsterkatze'), (4, 'Zibetkatze'), (4, 'Binturong'),
(4, 'Honigdachs'), (4, 'Vielfrass'), (4, 'Zobel'), (4, 'Nerz'), (4, 'Wiesel'),
(4, 'Hermelin'), (4, 'Iltis'), (4, 'Steinmarder'), (4, 'Baummarder'), (4, 'Fischermarder'),
(4, 'Tayra'), (4, 'Grison'), (4, 'Patagonienwiesel'), (4, 'Südamerikanischer'), (4, 'Riesenotter'),
(4, 'Seeotter'), (4, 'Eurasischer'), (4, 'Zwergotter'), (4, 'Glatthaarotter'), (4, 'Riesenbiber'),
(4, 'Bisamratte'), (4, 'Ondatra'), (4, 'Nutria'), (4, 'Chinchilla'), (4, 'Viscacha'),
(4, 'Degus'), (4, 'Chinchillaratte'), (4, 'Pakaratte'), (4, 'Aguti'), (4, 'Paka'),
(4, 'Capybara'), (4, 'Wasserschwein'), (4, 'Mara'), (4, 'Meerschweinchen'), (4, 'Cuy'),
(4, 'Präriehund'), (4, 'Ziesel'), (4, 'Murmeltier'), (4, 'Streifenhörnchen'), (4, 'Backenhörnchen'),
-- Weitere Vögel
(4, 'Kolibri'), (4, 'Eisvogel'), (4, 'Bienenfresser'), (4, 'Racke'), (4, 'Hoopoe'),
(4, 'Hornvogel'), (4, 'Tukan'), (4, 'Ara'), (4, 'Papagei'), (4, 'Wellensittich'),
(4, 'Nymphensittich'), (4, 'Kakadu'), (4, 'Lori'), (4, 'Amazone'), (4, 'Graupapagei'),
(4, 'Unzertrennliche'), (4, 'Agaporniden'), (4, 'Sperlingspapagei'), (4, 'Edelpapagei'), (4, 'Kea'),
(4, 'Kakapo'), (4, 'Fasan'), (4, 'Wachtel'), (1, 'Rebhuhn'), (4, 'Perlhuhn'),
(4, 'Pfau'), (4, 'Truthahn'), (4, 'Pute'), (4, 'Huhn'), (4, 'Hahn'),
(4, 'Strauss'), (4, 'Emu'), (4, 'Nandu'), (4, 'Kiwi'), (4, 'Kasuar'),
(4, 'Taube'), (4, 'Turteltaube'), (4, 'Ringeltaube'), (4, 'Türkentaube'), (4, 'Lachtaube'),
(4, 'Dodo'), (4, 'Wandertaube'), (4, 'Felsentaube'), (4, 'Hohltaube'), (4, 'Stadttaube'),
(4, 'Kiebitz'), (4, 'Brachvogel'), (4, 'Regenpfeifer'), (4, 'Sandpfeifer'), (4, 'Austernfischer'),
(4, 'Säbelschnäbler'), (4, 'Stelzenläufer'), (4, 'Kampfläufer'), (4, 'Goldregenpfeifer'), (4, 'Mornellregenpfeifer'),
(4, 'Steinwälzer'), (4, 'Knutt'), (4, 'Sanderling'), (4, 'Zwergstrandläufer'), (4, 'Temminckstrandläufer'),
-- Exotische Tiere
(4, 'Quetzal'), (4, 'Kondor'), (4, 'Kakapo'), (4, 'Schnabeltier'), (4, 'Ameisenigel'),
(4, 'Beutelteufel'), (4, 'Beutelwolf'), (4, 'Numbat'), (4, 'Quoll'), (4, 'Bandicoot'),
(4, 'Bilby'), (4, 'Potoroo'), (4, 'Bettong'), (4, 'Wallaby'), (4, 'Wallaroo'),
(4, 'Quokka'), (4, 'Pademelon'), (4, 'Felskänguru'), (4, 'Baumkänguru'), (4, 'Nagelkänguru'),
(4, 'Hasenkänguru'), (4, 'Ratkänguru'), (4, 'Kuskus'), (4, 'Gleitbeutler'), (4, 'Ringbeutler'),
(4, 'Beutelbär'), (4, 'Wombat'), (4, 'Haarnasenwombat'), (4, 'Bergwombat'), (4, 'Südlicher'),
(4, 'Okapi'), (4, 'Bongo'), (4, 'Sitatunga'), (4, 'Nyala'), (4, 'Buschbock'),
(4, 'Wasserbock'), (4, 'Pferdeantilope'), (4, 'Säbelantilope'), (4, 'Addax'), (4, 'Mendesantilope'),
(4, 'Dorkasgazelle'), (4, 'Thomsongazelle'), (4, 'Grantgazelle'), (4, 'Springgazelle'), (4, 'Gerenuk'),
(4, 'Dikdik'), (4, 'Klippspringer'), (4, 'Ducker'), (4, 'Oribi'), (4, 'Rehantilope');
